// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_feeds_join.sql

package database

import (
	"context"
)

const getAllFeedsWithCreatorUsername = `-- name: GetAllFeedsWithCreatorUsername :many
SELECT "feeds"."name", "feeds"."url", "users"."name" AS "user_name"
FROM "feeds"
JOIN "users"
ON "feeds"."user_id" = "users"."id"
`

type GetAllFeedsWithCreatorUsernameRow struct {
	Name     string
	Url      string
	UserName string
}

func (q *Queries) GetAllFeedsWithCreatorUsername(ctx context.Context) ([]GetAllFeedsWithCreatorUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeedsWithCreatorUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFeedsWithCreatorUsernameRow
	for rows.Next() {
		var i GetAllFeedsWithCreatorUsernameRow
		if err := rows.Scan(&i.Name, &i.Url, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
